name: ChestsPlusPlus
version: '${project.version}'
main: com.jamesdpeters.chestsplusplus.ChestsPlusPlus
api-version: 1.20
load: STARTUP
softdepend: [Parties]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlin.version}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlin.version}
  - org.springframework:spring-context:${spring.version}
  - org.springframework:spring-core:${spring.version}
  - javax.annotation:javax.annotation-api:${javax.annotation.version}
  - org.reflections:reflections:${reflections.version}