name: ChestsPlusPlus
version: '$version'
main: com.jamesdpeters.chestsplusplus.ChestsPlusPlus
api-version: 1.21
load: POSTWORLD
softdepend: [Parties]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlin_version}
  - org.jetbrains.kotlin:kotlin-reflect:${kotlin_version}
  - org.springframework:spring-context:${spring_version}
  - org.springframework:spring-core:${spring_version}
  - javax.annotation:javax.annotation-api:${javax_annotation_version}
  - org.reflections:reflections:${reflections_version}

permissions:
  chestlink.add:
    default: true
    description: Gives permission to add ChestLinks!
  chestlink.open:
    default: true
    description: Gives permission to open other people's ChestLinks!
  chestlink.menu:
    default: true
    description: Gives permission to open ChestLinks menu!
  chestlink.setpublic:
    default: true
    description: Gives permission to set ChestLinks public!